# Units: Weight is in Newtons, Size is surface area and is in m^2, and speed is in m/s
#
# note the dash in front
# each indentation is 2 spaces
- classic-nyan: # this is the id
  name: 'The OG Nyan Cat' # display name
  image: 'nyan.png' # no path information, just the image name
  speed: 4 # Use whatever units you want, just use the same across all
  size: 0.16 # Again, whatever units you want. eg: torso length / wingspan
  mass: 1 # don't know if we want this for extra information
  position:
    x: 0 # ignored for now
    y: 0 # height above (or below) the middle

- jackson-nyan:
  name: 'Moonwalking nyan'
  image: 'nyan-jackson.gif'
  speed: 8
  size: 0.64
  mass: 2
  position:
    x: 0
    y: 1000

- wandering-albatross:
  name: 'Wandering albatross'
  image: 'nyan-jackson.gif'
  speed: 19.22
  size: 0.62
  mass: 87
  position:
    x: 0
    y: -1000

- bald-eagle:
  name: 'Bald eagle'
  image: 'nyan-jackson.gif'
  speed: 12.76
  size: 0.76
  mass: 47
  position:
    x: 0
    y: 3000

- canada-goose:
  name: 'Canada goose'
  image: 'nyan-jackson.gif'
  speed: 23.15
  size: 0.28
  mass: 57
  position:
    x: 0
    y: -3000

- boeing-747:
  name: 'Boeing 747-400'
  image: 'nyan-jackson.gif'
  speed: 140.84
  size: 525
  mass: 3950000
  position:
    x: 0
    y: 5000

- blue-jay:
  name: 'Blue jay'
  image: 'nyan-jackson.gif'
  speed: 9.88
  size: 0.024
  mass: 0.89
  position:
    x: 0
    y: -1000

- swallowtail-butterfly:
  name: 'Swallowtail butterfly'
  image: 'nyan-jackson.gif'
  speed: 2.29
  size: 0.003
  mass: 0.006
  position:
    x: 0
    y: 500

- smaug:
  name: 'Smaug'
  image: 'nyan-jackson.gif'
  speed: 8.6
  size: 3175.44
  mass: 903393.81
  position:
    x: 0
    y: 30000
