# Units: Weight is in Newtons, Size is wing surface area and is in m^2, and speed is in m/s
#
# note the dash in front
# each indentation is 2 spaces
# - classic-nyan: # this is the id
#   name: 'The OG Nyan Cat' # display name
#   image: 'nyan.png' # no path information, just the image name
#   speed: 1 # Use whatever units you want, just use the same across all
#   size: 1 # Again, whatever units you want. eg: torso length / wingspan
#   mass: 1 # don't know if we want this for extra information
#   position:
#     x: 0 # ignored for now
#     y: 0 # height above (or below) the middle

- house-fly:
  name: 'House fly'
  image: 'Fly.png'
  speed: 0.84
  size: 0.00045
  mass: 0.00012
  position:
    x: 0
    y: -100

- dragonfly:
  name: 'Autumn darter dragonfly'
  image: 'Autumn-Darter-Dragonfly.png'
  speed: 0.28
  size: 0.001
  mass: 0.003
  position:
    x: 0
    y: -300

- blue-jay:
  name: 'Blue jay'
  image: 'Blue-Jay.png'
  speed: 9.88
  size: 0.024
  mass: 0.89
  position:
    x: 0
    y: -500

- little-brown-bat:
  name: 'Little brown bat'
  image: 'Little-Brown-Bat.png'
  speed: 4.33
  size: 0.01
  mass: 0.08
  position:
    x: 0
    y: -800

- canada-goose:
  name: 'Canada goose'
  image: 'Canada-Goose.png'
  speed: 23.15
  size: 0.28
  mass: 57
  position:
    x: 0
    y: -1300

- wandering-albatross:
  name: 'Wandering albatross'
  image: 'Wandering-Albatross.png'
  speed: 19.22
  size: 0.62
  mass: 87
  position:
    x: 0
    y: -2800

- quetzalcoatlus-pterosaur:
  name: 'Quetzalcoatlus pterosaur'
  image: 'Pterosaur.png'
  speed: 21.94
  size: 13.4
  mass: 2450
  position:
    x: 0
    y: -5300

- skyrim-dragon:
  name: 'Skyrim Dragon'
  image: 'Skyrim.png'
  speed: 79.58
  size: 20
  mass: 48,126.37
  position:
    x: 0
    y: -10100

- hungarian-horntail:
  name: 'Hungarian Horntail'
  image: 'Hungarian-Horntail.png'
  speed: 73.43
  size: 31
  mass: 63,519.84
  position:
    x: 0
    y: -21000


- boeing-747:
  name: 'Boeing 747-400'
  image: 'Boeing-747-400.png'
  speed: 140.84
  size: 525
  mass: 3950000
  position:
    x: 0
    y: -40000

- vermithrax:
  name: 'Vermithrax Pejorative'
  image: 'Vermithrax.png'
  speed: 81
  size: 240
  mass: 598,395.65
  position:
    x: 0
    y: -70000

- smaug:
  name: 'Smaug'
  image: 'Smaug.png'
  speed: 131.15
  size: 1600
  mass: 10,458,345.19
  position:
    x: 0
    y: -110000



# - drogon:
#   name: 'Drogon'
#   image: 'Fly.png'
#   speed: 131.01
#   size: 170
#   mass: 1,108,764.39
#   position:
#     x: 0
#     y: 30000
